server:
  port: 8083

spring:
  application:
    name: jpa-specification

  datasource:
    url: jdbc:postgresql://localhost:6000/jpa-specification
    username: dockerpostgres
    password: dockerpassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect